[terra-overlay] Fix CSP unsafe-inline violation.
cerner/terra-core pull request #3166
Opened 2020-09-21 10:49 UTC by pranav300

### Summary

This PR provides [inert styles](https://github.com/WICG/inert/pull/148/files#diff-04c6e90faac2675aa89e2176d2eec7d8R101-R111) as global styles and injects an empty link with id inert-style to head to avoid CSP violation

Closes #3165 

### Deployment Link

https://terra-core-deployed-pr-#.herokuapp.com/

### Testing

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

2020-09-21 13:04 UTC, emilyrohrbough approved these changes

2020-09-22 06:37 UTC, saket2403 approved these changes

2020-09-22 12:02 UTC, ShettyAkarsh approved these changes

2020-09-22 18:32 UTC, tbiethman approved these changes

2020-09-22 22:41 UTC, mjhenkes requested changes
We may not need this based on terra application changes

2020-09-23 18:18 UTC, pranav300 commented
Closing this PR, as this will be fixed by [terra-application PR-89](https://github.com/cerner/terra-application/pull/89)

2020-09-23 18:18 UTC, closed without merging