[terra-form-select] Adding attribute check in native select field to remove placeholder
cerner/terra-core pull request #3785
Opened 2023-04-24 07:59 UTC by AC086323

### Summary

Adding an attribute check to remove placeholder when isFilterStyle is added in selectAttrs of native select field

Closes #

### Testing

<img width="1357" alt="Screenshot 2023-04-24 at 13 27 58" src="https://user-images.githubusercontent.com/126561169/233934766-7796eb73-28c1-459f-befd-89cf7f34548b.png">

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

2023-04-27 05:24 UTC, saket2403 commented on packages/terra-form-select/src/native-select/NativeSelect.jsx
> +        {createPlaceholder(isFilterStyle, attrs, intl)}
You can pass `updatedIsFilterStyle` here and remove the conditions added in `createPlaceholder` function.
```suggestion
        {createPlaceholder(updatedIsFilterStyle, intl)}
```

2023-04-27 21:46 UTC, sdadn requested changes

2023-05-02 05:42 UTC, saket2403 commented on packages/terra-core-docs/CHANGELOG.md
> +>>>>>>> 061da1980 (Update packages/terra-core-docs/CHANGELOG.md)
Can you fix the merge conflicts here.

2023-05-04 04:59 UTC, saket2403 commented on packages/terra-form-select/CHANGELOG.md
> +  * Added attr check for isFilterStyle
```suggestion
  * Added `isFilterStyle` prop to native-select-field
```

2023-05-04 05:00 UTC, saket2403 approved these changes

2023-05-05 05:15 UTC, merged