[terra-status-view] update font size
cerner/terra-core pull request #3799
Opened 2023-05-17 08:03 UTC by PK106552

**What was changed:**
Changed title font size as per OpenSource Theme

**Why it was changed:**
Title font size is not matching as per OpenSource Theme

---

Thank you for contributing to Terra.
@cerner/terra

2023-05-17 09:36 UTC, sugan2416 approved these changes

2023-06-02 21:45 UTC, sdadn requested changes

2023-06-02 21:45 UTC, sdadn commented on package.json
> +    "moment": "^2.29.4"
Why is this being added?
```suggestion
  },
  "dependencies": {
    "moment": "^2.29.4"
```

2023-06-02 21:45 UTC, sdadn commented on packages/terra-core-docs/CHANGELOG.md
> +
This entry is not necessary for the `terra-core-docs` package.

2023-06-06 06:46 UTC, closed without merging

2023-06-06 06:46 UTC, PK106552 commented
No longer required