[terra-form-textarea] add `aria-invalid` field
cerner/terra-core pull request #3841
Opened 2023-07-11 08:19 UTC by razvanluca

### Summary

Added `aria-invalid` field to mark what field is invalid for screen readers

**What was changed:**
Added `aria-invalid` field to [terra-form-textarea]

**Why it was changed:**
Added `aria-invalid` field to mark what field is invalid for screen readers

### Testing

This change was tested using:

- [ ] WDIO
- [x] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [x] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-8681

---

Thank you for contributing to Terra.
@cerner/terra

2023-07-13 20:39 UTC, sdadn commented on packages/terra-form-textarea/CHANGELOG.md
> +* Added `aria-invalid` field to Textarea component and changed existing example so it can be tested
We don't need to talk about examples outside of the docs CHANGELOG.
```suggestion
* Added
  * Added support for `aria-invalid` through the `IsInvalid` prop to mark what field is invalid for assistive technology.
```

2023-07-14 21:12 UTC, sdadn approved these changes

2023-07-17 16:04 UTC, sycombs requested changes

2023-07-17 16:04 UTC, sycombs commented on packages/terra-form-textarea/CHANGELOG.md
> +  * Added support for `aria-invalid` through the `IsInvalid` prop to mark what field is invalid for assistive technology.
nit: capitalization of the prop name
```suggestion
  * Added support for `aria-invalid` through the `isInvalid` prop to mark what field is invalid for assistive technology.
```

2023-07-17 16:04 UTC, sycombs commented on packages/terra-form-textarea/src/Textarea.jsx
> +    additionalTextareaProps['aria-invalid'] = isInvalid;
Can we add a Jest test case for the value of the 'aria-invalid' when `isInvalid` is true?

2023-07-18 18:37 UTC, sdadn approved these changes

2023-07-19 12:20 UTC, supreethmr reviewed
Just curious we other input field components like terra-input-field and form-select-field component and they do communicate invalid state without `aria-invalid` attribute. so are we adding this attribute to fix any specific screen-reader browser combination OR adding it as part of best practice..??

2023-07-19 12:35 UTC, razvanluca commented
> Just curious we other input field components like terra-input-field and form-select-field component and they do communicate invalid state without `aria-invalid` attribute. so are we adding this attribute to fix any specific screen-reader browser combination OR adding it as part of best practice..??

I did a test with Jaws screen reader and checked with @scottwilmarth what's the expected behavior of an invalid form-textarea and he told me about aria-invalid field. @scottwilmarth , do you want to add something on this topic?

2023-07-19 21:12 UTC, scottwilmarth commented
Adding my +1 after reviewing example. I updated UX and accessibility labels.

2023-07-20 12:04 UTC, razvanluca commented
I changed the initial Jira that was a spike to the current Epic, UXPLATFORM-9356 in the PR comment

2023-07-21 12:08 UTC, supreethmr approved these changes

2023-07-21 21:35 UTC, merged