Terra arrange issue fixed
cerner/terra-core pull request #3846
Opened 2023-07-13 13:56 UTC by gt106551

**Summary**
 Please ensure that to test this with terra arrange:-
1.Ensure that terra arrange support altering multiple CSS attributes without loss of function or information.
2.Ensure that terra arrange support resizing to 400%.
3.Ensure that terra arrange support reflow when the viewport is resized to 320x256 px without loss of information or functio

**_**Solution**_**
I have made changes in Arrange.module.scss

    max-width: 100%;
    overflow: auto;
    max-height: 100%;
    
   [UXPLATFORM-8662]

Thank you for contributing to Terra.
**@cerner/terra**

2023-07-13 16:07 UTC, sdadn commented
How was this tested?

2023-07-13 17:33 UTC, mjpalazzo commented
Where did the 400% requirement come from? Per WCAG text should be able to size to 200%. See WCAG 1.4.4 Resize Text Level AA: [https://www.w3.org/WAI/WCAG21/Techniques/general/G178.html]

2023-07-13 17:53 UTC, gt106551 commented
> Where did the 400% requirement come from? Per WCAG text should be able to size to 200%. See WCAG 1.4.4 Resize Text Level AA: [https://www.w3.org/WAI/WCAG21/Techniques/general/G178.html]



I got a comment on jira  from UX team regarding this changes.
[https://jira2.cerner.com/browse/UXPLATFORM-8662](url)

2023-07-14 11:39 UTC, rahulkumar8cs commented
@mjpalazzo  400% browser Zoom needs to be validated in order to meet the WCAG 2.1 [1.4.10 Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) requirement.

2023-07-14 13:37 UTC, mjpalazzo commented
Thanks for your response @rahulkumar8cs. I think the requirement in the Summary is not stated correctly. The intent of WCAG 1.4.10 is "When the browser zoom is used to scale content to 400%, it reflows - i.e., it is presented in one column so that scrolling in more than one direction is not necessary." That is different from what the summary says, "Ensure that Terra Arrange supports resizing to 400%" I think the requirement is that Terra Arrange reflows to one column when zoomed to 400%. The goal is to avoid the need for the user to scroll.

2023-07-14 21:10 UTC, sdadn requested changes

2023-07-14 21:10 UTC, sdadn commented on packages/terra-arrange/CHANGELOG.md
> +  * Fixed issue terra arrange support resizing to 400% and viewport is resized to 320x256 px without loss of information or function.
```suggestion
* Fixed
  * Fixed reflow issue when zoomed to 400% and the viewport is resized to 320x256 px.
```

2023-07-17 08:25 UTC, gt106551 commented on packages/terra-arrange/CHANGELOG.md
> +  * Fixed issue terra arrange support resizing to 400% and viewport is resized to 320x256 px without loss of information or function.
i have made changes as per suggestion.

2023-07-19 04:41 UTC, supreethmr approved these changes

2023-07-21 04:55 UTC, saket2403 approved these changes

2023-07-21 05:01 UTC, ShettyAkarsh commented
@gt106551  is this changes tested for different zoom size and viewpors ?

2023-07-21 05:11 UTC, gt106551 commented
> @gt106551 is this changes tested for different zoom size and viewpors ?

@ShettyAkarsh yes i have tested with different zoom size and viewport.

2023-07-21 05:55 UTC, merged