[terra-scroll] Added realistic examples
cerner/terra-core pull request #3876
Opened 2023-08-11 11:02 UTC by AH106586Harika

### Summary

**What was changed:**
Removed some generic content and added realistic content with interactive elements.

**Why it was changed:**
As the examples are generic changed to realistic examples.

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

**This PR resolves:**

[UXPLATFORM-9462](https://jira2.cerner.com/browse/UXPLATFORM-9462)

---

Thank you for contributing to Terra.
@cerner/terra

2023-08-14 04:54 UTC, supreethmr commented on packages/terra-core-docs/CHANGELOG.md
> +  * Updated `terra-scroll` to add realistic examples.
```suggestion

* Updated
  * Updated `terra-scroll` to add realistic examples.
```

2023-08-14 13:53 UTC, adoroshk reviewed
Before the change the vertical scroll example had only vertical scroll and horizontal scroll example had only horizontal scroll. When I tested this change, both examples had both, horizontal and vertical scrolls. It might be an expected behavior for the horizontal scroll in case of content being bigger than container, but doesn't look like expected behavior for the vertical scroll container to have a horysontal scroll. Please correct me if I am wrong. 

Also it might look better if the input and button have same padding ad paragraph for consistancy.

<img width="455" alt="Screenshot 2023-08-14 at 9 45 05 AM" src="https://github.com/cerner/terra-core/assets/119358186/60e02d51-8ecc-4b25-890e-bb8f75667fa4">
<img width="437" alt="Screenshot 2023-08-14 at 9 48 18 AM" src="https://github.com/cerner/terra-core/assets/119358186/ece97b4f-1697-40a6-98a1-c74afdef2d37">

2023-08-17 05:57 UTC, AH106586Harika commented on packages/terra-core-docs/CHANGELOG.md
> +  * Updated `terra-scroll` to add realistic examples.
Done.

2023-08-17 06:23 UTC, AH106586Harika commented
> Before the change the vertical scroll example had only vertical scroll and horizontal scroll example had only horizontal scroll. When I tested this change, both examples had both, horizontal and vertical scrolls. It might be an expected behavior for the horizontal scroll in case of content being bigger than container, but doesn't look like expected behavior for the vertical scroll container to have a horysontal scroll. Please correct me if I am wrong.
> 
> Also it might look better if the input and button have same padding ad paragraph for consistancy.
> 
> <img alt="Screenshot 2023-08-14 at 9 45 05 AM" width="455" src="https://user-images.githubusercontent.com/119358186/260465443-60e02d51-8ecc-4b25-890e-bb8f75667fa4.png"> <img alt="Screenshot 2023-08-14 at 9 48 18 AM" width="437" src="https://user-images.githubusercontent.com/119358186/260465764-ece97b4f-1697-40a6-98a1-c74afdef2d37.png"


> Before the change the vertical scroll example had only vertical scroll and horizontal scroll example had only horizontal scroll. When I tested this change, both examples had both, horizontal and vertical scrolls. It might be an expected behavior for the horizontal scroll in case of content being bigger than container, but doesn't look like expected behavior for the vertical scroll container to have a horysontal scroll. Please correct me if I am wrong.
> 
> Also it might look better if the input and button have same padding ad paragraph for consistancy.
> 
> <img alt="Screenshot 2023-08-14 at 9 45 05 AM" width="455" src="https://user-images.githubusercontent.com/119358186/260465443-60e02d51-8ecc-4b25-890e-bb8f75667fa4.png"> <img alt="Screenshot 2023-08-14 at 9 48 18 AM" width="437" src="https://user-images.githubusercontent.com/119358186/260465764-ece97b4f-1697-40a6-98a1-c74afdef2d37.png">



Removed horizontal scroll for vertical scroll and reduced content, also removed vertical scroll for horizontal scroll, added padding as suggested for input and submit

2023-08-18 19:28 UTC, adoroshk requested changes
I suggest simplifying the `Scroll` content to be:

<div className={cx('paragraph-x-wrapper')}>
    <p>
      Entering patient details is a crucial process in healthcare facilities that involves capturing and documenting relevant information about
      individuals seeking medical care. Patient details need to be regularly updated to ensure accuracy and relevancy. This may involve periodic
      verification of personal information, updating medical history, and making necessary changes to insurance or contact details.
    </p>
    <InputField
        inputId="input-field"
        label="Enter Patient Name"
        type="text"
    />
    <Button text="Submit" />
</div>

In this case we don't need `container-x-wrapper` class.

2023-08-22 05:04 UTC, supreethmr approved these changes

2023-08-22 21:58 UTC, sdadn approved these changes

2023-08-25 11:18 UTC, kademswetha commented
+1

2023-08-28 02:37 UTC, merged