single-select-issues
cerner/terra-core pull request #3906
Opened 2023-09-12 09:43 UTC by gt106551

### Summary

**What was changed:**

**Why it was changed:**

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-XXXX 

---

Thank you for contributing to Terra.
@cerner/terra

2023-09-14 03:37 UTC, sdadn requested changes

2023-09-14 03:37 UTC, sdadn commented on packages/terra-form-select/src/single/Menu.jsx
> +    } else if ((keyCode === KeyCode.KEY_RETURN || keyCode === KeyCode.KEY_SPACE) && active !== null) {
there needs to be a test for space

2023-09-14 03:37 UTC, sdadn commented on packages/terra-form-select/CHANGELOG.md
> +  * Fixed selection did not work with space-key `form-single-select`.
```suggestion
  * Fixed selection not working with space key in `form-single-select`.
```

2023-09-14 03:37 UTC, sdadn commented on packages/terra-form-select/CHANGELOG.md
> +  * Fixed Enter did not work to expand the combo box example `form-single-select` .
```suggestion
  * Fixed enter key not expanding the combo box in `form-single-select` .
```

2023-09-14 07:09 UTC, gt106551 commented on packages/terra-form-select/src/single/Menu.jsx
> +    } else if ((keyCode === KeyCode.KEY_RETURN || keyCode === KeyCode.KEY_SPACE) && active !== null) {
Added a test case for this

2023-09-14 07:09 UTC, gt106551 commented on packages/terra-form-select/CHANGELOG.md
> +  * Fixed selection did not work with space-key `form-single-select`.
updated

2023-09-14 07:09 UTC, gt106551 commented on packages/terra-form-select/CHANGELOG.md
> +  * Fixed Enter did not work to expand the combo box example `form-single-select` .
updated

2023-09-14 10:38 UTC, supreethmr commented on packages/terra-form-select/tests/wdio/select-spec.js
> +        browser.keys('Enter');
why do we need an enter to close the dropdown

2023-09-14 10:41 UTC, supreethmr commented on packages/terra-form-select/CHANGELOG.md
> +  * Fixed enter key not expanding the combo box in `form-single-select` .
```suggestion

* Fixed
   * Fixed selection not working with space key in `form-single-select`.
   * Fixed enter key not expanding the combo box in `form-single-select` .
```

2023-09-14 12:08 UTC, supreethmr commented on packages/terra-form-select/tests/wdio/select-spec.js
> +      });
we can remove this block !!

2023-09-14 12:09 UTC, supreethmr commented on packages/terra-form-select/tests/wdio/select-spec.js
> +      });
```suggestion
```
let's remove this block

2023-09-14 13:27 UTC, gt106551 commented on packages/terra-form-select/CHANGELOG.md
> +  * Fixed enter key not expanding the combo box in `form-single-select` .
Updated.

2023-09-14 13:28 UTC, gt106551 commented on packages/terra-form-select/tests/wdio/select-spec.js
> +      });
updated.

2023-09-14 18:45 UTC, supreethmr approved these changes

2023-09-15 05:10 UTC, saket2403 approved these changes

2023-09-15 06:08 UTC, merged